#!/bin/bash

echo "please, enter your PIN NUMBER"
# Here pin number is a variable
read -s PIN_NUMBER # -s means don't display the number 

#we generally don't print the pin number in real time scenario, here we are printing for practice purpose
echo "PIN Entered is: $PIN_NUMBER"